mod input;
mod parser;
mod slr;
mod token;
mod tree;
mod ruleparser;

use token::*;

use crate::{input::read_input, ruleparser::{reader::parse_rules, structs::RawProduction}, slr::parser::{NonterminalSymbol, Production, Productions, Symbol, TerminalSymbol}};

#[derive(PartialEq, Eq, Debug, Default, Clone, Hash)]
pub enum Expression {
    Token(Token),
    #[default]
    CODE,
    VDECL,
    ASSIGN,
    RHS,
    EXPR,
    HIGHOP,
    LOWOP,
    OPERAND,
    FDECL,
    ARG,
    MOREARGS,
    BLOCK,
    STMT,
    COND,
    RCOND,
    ELSE,
    RETURN,
    CDECL,
    ODECL,
}

fn get_rules() -> Productions {
    Productions::from([
        Production::new(
            NonterminalSymbol::Code,
            vec![
                Symbol::Nonterminal(NonterminalSymbol::VDecl),
                Symbol::Nonterminal(NonterminalSymbol::Code),
            ],
        ),
        Production::new(
            NonterminalSymbol::Code,
            vec![
                Symbol::Nonterminal(NonterminalSymbol::FDecl),
                Symbol::Nonterminal(NonterminalSymbol::Code),
            ],
        ),
        Production::new(
            NonterminalSymbol::Code,
            vec![
                Symbol::Nonterminal(NonterminalSymbol::CDecl),
                Symbol::Nonterminal(NonterminalSymbol::Code),
            ],
        ),
        Production::new(NonterminalSymbol::Code, vec![]),
        Production::new(
            NonterminalSymbol::VDecl,
            vec![
                Symbol::Terminal(TerminalSymbol::Vtype),
                Symbol::Terminal(TerminalSymbol::Id),
                Symbol::Terminal(TerminalSymbol::Semi),
            ],
        ),
        Production::new(
            NonterminalSymbol::VDecl,
            vec![
                Symbol::Terminal(TerminalSymbol::Vtype),
                Symbol::Nonterminal(NonterminalSymbol::Assign),
                Symbol::Terminal(TerminalSymbol::Semi),
            ],
        ),
        Production::new(
            NonterminalSymbol::Assign,
            vec![
                Symbol::Terminal(TerminalSymbol::Id),
                Symbol::Terminal(TerminalSymbol::Assign),
                Symbol::Nonterminal(NonterminalSymbol::Rhs),
            ],
        ),
        Production::new(
            NonterminalSymbol::Rhs,
            vec![Symbol::Nonterminal(NonterminalSymbol::HighOp)],
        ),
        Production::new(
            NonterminalSymbol::Rhs,
            vec![Symbol::Terminal(TerminalSymbol::Literal)],
        ),
        Production::new(
            NonterminalSymbol::Rhs,
            vec![Symbol::Terminal(TerminalSymbol::Character)],
        ),
        Production::new(
            NonterminalSymbol::Rhs,
            vec![Symbol::Terminal(TerminalSymbol::Boolstr)],
        ),
        Production::new(
            NonterminalSymbol::HighOp,
            vec![
                Symbol::Nonterminal(NonterminalSymbol::HighOp),
                Symbol::Terminal(TerminalSymbol::Addsub),
                Symbol::Nonterminal(NonterminalSymbol::LowOp),
            ],
        ),
        Production::new(
            NonterminalSymbol::HighOp,
            vec![Symbol::Nonterminal(NonterminalSymbol::LowOp)],
        ),
        Production::new(
            NonterminalSymbol::LowOp,
            vec![
                Symbol::Nonterminal(NonterminalSymbol::LowOp),
                Symbol::Terminal(TerminalSymbol::Multdiv),
                Symbol::Nonterminal(NonterminalSymbol::Operand),
            ],
        ),
        Production::new(
            NonterminalSymbol::LowOp,
            vec![Symbol::Nonterminal(NonterminalSymbol::Operand)],
        ),
        Production::new(
            NonterminalSymbol::Operand,
            vec![
                Symbol::Terminal(TerminalSymbol::Lparen),
                Symbol::Nonterminal(NonterminalSymbol::HighOp),
                Symbol::Terminal(TerminalSymbol::Rparen),
            ],
        ),
        Production::new(
            NonterminalSymbol::LowOp,
            vec![Symbol::Terminal(TerminalSymbol::Id)],
        ),
        Production::new(
            NonterminalSymbol::LowOp,
            vec![Symbol::Terminal(TerminalSymbol::Num)],
        ),
        Production::new(
            NonterminalSymbol::FDecl,
            vec![
                Symbol::Terminal(TerminalSymbol::Vtype),
                Symbol::Terminal(TerminalSymbol::Id),
                Symbol::Terminal(TerminalSymbol::Lparen),
                Symbol::Nonterminal(NonterminalSymbol::Arg),
                Symbol::Terminal(TerminalSymbol::Rparen),
                Symbol::Terminal(TerminalSymbol::Lbrace),
                Symbol::Nonterminal(NonterminalSymbol::Block),
                Symbol::Nonterminal(NonterminalSymbol::Return),
                Symbol::Terminal(TerminalSymbol::Rbrace),
            ],
        ),
        Production::new(
            NonterminalSymbol::Arg,
            vec![
                Symbol::Terminal(TerminalSymbol::Vtype),
                Symbol::Terminal(TerminalSymbol::Id),
                Symbol::Nonterminal(NonterminalSymbol::MoreArgs),
            ],
        ),
        Production::new(NonterminalSymbol::Arg, vec![]),
        Production::new(
            NonterminalSymbol::MoreArgs,
            vec![
                Symbol::Terminal(TerminalSymbol::Comma),
                Symbol::Terminal(TerminalSymbol::Vtype),
                Symbol::Terminal(TerminalSymbol::Id),
                Symbol::Nonterminal(NonterminalSymbol::MoreArgs),
            ],
        ),
        Production::new(NonterminalSymbol::MoreArgs, vec![]),
        Production::new(
            NonterminalSymbol::Block,
            vec![
                Symbol::Nonterminal(NonterminalSymbol::Stmt),
                Symbol::Nonterminal(NonterminalSymbol::Block),
            ],
        ),
        Production::new(NonterminalSymbol::Block, vec![]),
        Production::new(
            NonterminalSymbol::Stmt,
            vec![Symbol::Nonterminal(NonterminalSymbol::VDecl)],
        ),
        Production::new(
            NonterminalSymbol::Stmt,
            vec![
                Symbol::Nonterminal(NonterminalSymbol::Assign),
                Symbol::Terminal(TerminalSymbol::Semi),
            ],
        ),
        Production::new(
            NonterminalSymbol::Stmt,
            vec![
                Symbol::Terminal(TerminalSymbol::If),
                Symbol::Terminal(TerminalSymbol::Lparen),
                Symbol::Nonterminal(NonterminalSymbol::Cond),
                Symbol::Terminal(TerminalSymbol::Rparen),
                Symbol::Terminal(TerminalSymbol::Lbrace),
                Symbol::Nonterminal(NonterminalSymbol::Block),
                Symbol::Terminal(TerminalSymbol::Rbrace),
                Symbol::Nonterminal(NonterminalSymbol::Else),
            ],
        ),
        Production::new(
            NonterminalSymbol::Stmt,
            vec![
                Symbol::Terminal(TerminalSymbol::While),
                Symbol::Terminal(TerminalSymbol::Lparen),
                Symbol::Nonterminal(NonterminalSymbol::Cond),
                Symbol::Terminal(TerminalSymbol::Rparen),
                Symbol::Terminal(TerminalSymbol::Lbrace),
                Symbol::Nonterminal(NonterminalSymbol::Block),
                Symbol::Terminal(TerminalSymbol::Rbrace),
            ],
        ),
        Production::new(
            NonterminalSymbol::Cond,
            vec![
                Symbol::Nonterminal(NonterminalSymbol::Cond),
                Symbol::Terminal(TerminalSymbol::Comp),
                Symbol::Nonterminal(NonterminalSymbol::RCond),
            ],
        ),
        Production::new(
            NonterminalSymbol::Cond,
            vec![Symbol::Nonterminal(NonterminalSymbol::RCond)],
        ),
        Production::new(
            NonterminalSymbol::RCond,
            vec![Symbol::Terminal(TerminalSymbol::Boolstr)],
        ),
        Production::new(
            NonterminalSymbol::Else,
            vec![
                Symbol::Terminal(TerminalSymbol::Else),
                Symbol::Terminal(TerminalSymbol::Lbrace),
                Symbol::Nonterminal(NonterminalSymbol::Block),
                Symbol::Terminal(TerminalSymbol::Rbrace),
            ],
        ),
        Production::new(NonterminalSymbol::Else, vec![]),
        Production::new(
            NonterminalSymbol::Return,
            vec![
                Symbol::Terminal(TerminalSymbol::Return),
                Symbol::Nonterminal(NonterminalSymbol::Rhs),
                Symbol::Terminal(TerminalSymbol::Semi),
            ],
        ),
        Production::new(
            NonterminalSymbol::CDecl,
            vec![
                Symbol::Terminal(TerminalSymbol::Class),
                Symbol::Terminal(TerminalSymbol::Id),
                Symbol::Terminal(TerminalSymbol::Lbrace),
                Symbol::Nonterminal(NonterminalSymbol::ODecl),
                Symbol::Terminal(TerminalSymbol::Rbrace),
            ],
        ),
        Production::new(
            NonterminalSymbol::ODecl,
            vec![
                Symbol::Nonterminal(NonterminalSymbol::VDecl),
                Symbol::Nonterminal(NonterminalSymbol::ODecl),
            ],
        ),
        Production::new(
            NonterminalSymbol::ODecl,
            vec![
                Symbol::Nonterminal(NonterminalSymbol::FDecl),
                Symbol::Nonterminal(NonterminalSymbol::ODecl),
            ],
        ),
        Production::new(NonterminalSymbol::ODecl, vec![]),
    ])
}

fn get_test_rules() -> slr::parser::Productions {
    Productions::from([
        Production::new(
            NonterminalSymbol::Code,
            vec![
                Symbol::Nonterminal(NonterminalSymbol::VDecl),
                Symbol::Nonterminal(NonterminalSymbol::Code),
            ],
        ),
        Production::new(
            NonterminalSymbol::Code,
            vec![
                Symbol::Terminal(TerminalSymbol::Vtype),
                Symbol::Nonterminal(NonterminalSymbol::Assign),
            ],
        ),
        Production::new(NonterminalSymbol::Code, vec![]),
        Production::new(
            NonterminalSymbol::VDecl,
            vec![
                Symbol::Terminal(TerminalSymbol::Vtype),
                Symbol::Terminal(TerminalSymbol::Id),
                Symbol::Terminal(TerminalSymbol::Semi),
            ],
        ),
        Production::new(
            NonterminalSymbol::VDecl,
            vec![
                Symbol::Terminal(TerminalSymbol::Vtype),
                Symbol::Nonterminal(NonterminalSymbol::Assign),
                Symbol::Terminal(TerminalSymbol::Semi),
            ],
        ),
        Production::new(
            NonterminalSymbol::Assign,
            vec![
                Symbol::Terminal(TerminalSymbol::Id),
                Symbol::Terminal(TerminalSymbol::Assign),
            ],
        ),
    ])
}
fn main() {
    // let parser = slr::parser::LRTable::new(&get_rules());
    let mut rules = ruleparser::structs::TokenManager::new();
    let input = read_input();
    let rules_input = parse_rules(&input);
    rules.add_productions(&rules_input);
    println!("{}", rules);
    println!("{:?}", rules);
}
