mod input;
mod parser;
mod slr;
mod token;
mod tree;

use token::*;

use crate::slr::parser::{NonterminalSymbol, Productions, Symbol, TerminalSymbol};

#[derive(PartialEq, Eq, Debug, Default, Clone, Hash)]
pub enum Expression {
    Token(Token),
    #[default]
    CODE,
    VDECL,
    ASSIGN,
    RHS,
    EXPR,
    HIGHOP,
    LOWOP,
    OPERAND,
    FDECL,
    ARG,
    MOREARGS,
    BLOCK,
    STMT,
    COND,
    RCOND,
    ELSE,
    RETURN,
    CDECL,
    ODECL,
}

fn get_rules() -> slr::parser::Rules {
    slr::parser::Rules {
        start: NonterminalSymbol::Code,
        productions: Productions::from([
            (
                NonterminalSymbol::Code,
                vec![
                    vec![
                        Symbol::Nonterminal(NonterminalSymbol::VDecl),
                        Symbol::Nonterminal(NonterminalSymbol::Code),
                    ],
                    vec![
                        Symbol::Nonterminal(NonterminalSymbol::FDecl),
                        Symbol::Nonterminal(NonterminalSymbol::Code),
                    ],
                    vec![
                        Symbol::Nonterminal(NonterminalSymbol::CDecl),
                        Symbol::Nonterminal(NonterminalSymbol::Code),
                    ],
                    vec![],
                ],
            ),
            (
                NonterminalSymbol::VDecl,
                vec![
                    vec![
                        Symbol::Terminal(TerminalSymbol::Vtype),
                        Symbol::Terminal(TerminalSymbol::Id),
                        Symbol::Terminal(TerminalSymbol::Semi),
                    ],
                    vec![
                        Symbol::Terminal(TerminalSymbol::Vtype),
                        Symbol::Nonterminal(NonterminalSymbol::Assign),
                        Symbol::Terminal(TerminalSymbol::Semi),
                    ],
                ],
            ),
            (
                NonterminalSymbol::Assign,
                vec![vec![
                    Symbol::Terminal(TerminalSymbol::Id),
                    Symbol::Terminal(TerminalSymbol::Assign),
                    Symbol::Nonterminal(NonterminalSymbol::Rhs),
                ]],
            ),
            (
                NonterminalSymbol::Rhs,
                vec![
                    vec![Symbol::Nonterminal(NonterminalSymbol::HighOp)],
                    vec![Symbol::Terminal(TerminalSymbol::Literal)],
                    vec![Symbol::Terminal(TerminalSymbol::Character)],
                    vec![Symbol::Terminal(TerminalSymbol::Boolstr)],
                ],
            ),
            (
                NonterminalSymbol::HighOp,
                vec![
                    vec![
                        Symbol::Nonterminal(NonterminalSymbol::HighOp),
                        Symbol::Terminal(TerminalSymbol::Addsub),
                        Symbol::Nonterminal(NonterminalSymbol::LowOp),
                    ],
                    vec![Symbol::Nonterminal(NonterminalSymbol::LowOp)],
                ],
            ),
            (
                NonterminalSymbol::LowOp,
                vec![
                    vec![
                        Symbol::Nonterminal(NonterminalSymbol::LowOp),
                        Symbol::Terminal(TerminalSymbol::Multdiv),
                        Symbol::Nonterminal(NonterminalSymbol::Operand),
                    ],
                    vec![Symbol::Nonterminal(NonterminalSymbol::Operand)],
                ],
            ),
            (
                NonterminalSymbol::Operand,
                vec![
                    vec![
                        Symbol::Terminal(TerminalSymbol::Lparen),
                        Symbol::Nonterminal(NonterminalSymbol::HighOp),
                        Symbol::Terminal(TerminalSymbol::Rparen),
                    ],
                    vec![Symbol::Terminal(TerminalSymbol::Id)],
                    vec![Symbol::Terminal(TerminalSymbol::Num)],
                ],
            ),
            (
                NonterminalSymbol::FDecl,
                vec![vec![
                    Symbol::Terminal(TerminalSymbol::Vtype),
                    Symbol::Terminal(TerminalSymbol::Id),
                    Symbol::Terminal(TerminalSymbol::Lparen),
                    Symbol::Nonterminal(NonterminalSymbol::Arg),
                    Symbol::Terminal(TerminalSymbol::Rparen),
                    Symbol::Terminal(TerminalSymbol::Lbrace),
                    Symbol::Nonterminal(NonterminalSymbol::Block),
                    Symbol::Nonterminal(NonterminalSymbol::Return),
                    Symbol::Terminal(TerminalSymbol::Rbrace),
                ]],
            ),
            (
                NonterminalSymbol::Arg,
                vec![
                    vec![
                        Symbol::Terminal(TerminalSymbol::Vtype),
                        Symbol::Terminal(TerminalSymbol::Id),
                        Symbol::Nonterminal(NonterminalSymbol::MoreArgs),
                    ],
                    vec![],
                ],
            ),
            (
                NonterminalSymbol::MoreArgs,
                vec![
                    vec![
                        Symbol::Terminal(TerminalSymbol::Comma),
                        Symbol::Terminal(TerminalSymbol::Vtype),
                        Symbol::Terminal(TerminalSymbol::Id),
                        Symbol::Nonterminal(NonterminalSymbol::MoreArgs),
                    ],
                    vec![],
                ],
            ),
            (
                NonterminalSymbol::Block,
                vec![
                    vec![
                        Symbol::Nonterminal(NonterminalSymbol::Stmt),
                        Symbol::Nonterminal(NonterminalSymbol::Block),
                    ],
                    vec![],
                ],
            ),
            (
                NonterminalSymbol::Stmt,
                vec![
                    vec![Symbol::Nonterminal(NonterminalSymbol::VDecl)],
                    vec![
                        Symbol::Nonterminal(NonterminalSymbol::Assign),
                        Symbol::Terminal(TerminalSymbol::Semi),
                    ],
                    vec![
                        Symbol::Terminal(TerminalSymbol::If),
                        Symbol::Terminal(TerminalSymbol::Lparen),
                        Symbol::Nonterminal(NonterminalSymbol::Cond),
                        Symbol::Terminal(TerminalSymbol::Rparen),
                        Symbol::Terminal(TerminalSymbol::Lbrace),
                        Symbol::Nonterminal(NonterminalSymbol::Block),
                        Symbol::Terminal(TerminalSymbol::Rbrace),
                        Symbol::Nonterminal(NonterminalSymbol::Else),
                    ],
                    vec![
                        Symbol::Terminal(TerminalSymbol::While),
                        Symbol::Terminal(TerminalSymbol::Lparen),
                        Symbol::Nonterminal(NonterminalSymbol::Cond),
                        Symbol::Terminal(TerminalSymbol::Rparen),
                        Symbol::Terminal(TerminalSymbol::Lbrace),
                        Symbol::Nonterminal(NonterminalSymbol::Block),
                        Symbol::Terminal(TerminalSymbol::Rbrace),
                    ],
                ],
            ),
            (
                NonterminalSymbol::Cond,
                vec![
                    vec![
                        Symbol::Nonterminal(NonterminalSymbol::Cond),
                        Symbol::Terminal(TerminalSymbol::Comp),
                        Symbol::Nonterminal(NonterminalSymbol::RCond),
                    ],
                    vec![Symbol::Nonterminal(NonterminalSymbol::RCond)],
                ],
            ),
            (
                NonterminalSymbol::RCond,
                vec![vec![Symbol::Terminal(TerminalSymbol::Boolstr)]],
            ),
            (
                NonterminalSymbol::Else,
                vec![
                    vec![
                        Symbol::Terminal(TerminalSymbol::Else),
                        Symbol::Terminal(TerminalSymbol::Lbrace),
                        Symbol::Nonterminal(NonterminalSymbol::Block),
                        Symbol::Terminal(TerminalSymbol::Rbrace),
                    ],
                    vec![],
                ],
            ),
            (
                NonterminalSymbol::Return,
                vec![vec![
                    Symbol::Terminal(TerminalSymbol::Return),
                    Symbol::Nonterminal(NonterminalSymbol::Rhs),
                    Symbol::Terminal(TerminalSymbol::Semi),
                ]],
            ),
            (
                NonterminalSymbol::CDecl,
                vec![vec![
                    Symbol::Terminal(TerminalSymbol::Class),
                    Symbol::Terminal(TerminalSymbol::Id),
                    Symbol::Terminal(TerminalSymbol::Lbrace),
                    Symbol::Nonterminal(NonterminalSymbol::ODecl),
                    Symbol::Terminal(TerminalSymbol::Rbrace),
                ]],
            ),
            (
                NonterminalSymbol::ODecl,
                vec![
                    vec![
                        Symbol::Nonterminal(NonterminalSymbol::VDecl),
                        Symbol::Nonterminal(NonterminalSymbol::ODecl),
                    ],
                    vec![
                        Symbol::Nonterminal(NonterminalSymbol::FDecl),
                        Symbol::Nonterminal(NonterminalSymbol::ODecl),
                    ],
                    vec![],
                ],
            ),
        ]),
    }
}

fn get_test_rules() -> slr::parser::Rules {
    slr::parser::Rules {
        start: NonterminalSymbol::Code,
        productions: Productions::from([
            (
                NonterminalSymbol::Code,
                vec![
                    vec![
                        Symbol::Nonterminal(NonterminalSymbol::VDecl),
                        Symbol::Nonterminal(NonterminalSymbol::Code),
                    ],
                    vec![],
                    vec![
                        Symbol::Terminal(TerminalSymbol::Vtype),
                        Symbol::Nonterminal(NonterminalSymbol::Assign),
                    ],
                    vec![],
                ],
            ),
            (
                NonterminalSymbol::VDecl,
                vec![
                    vec![
                        Symbol::Terminal(TerminalSymbol::Vtype),
                        Symbol::Terminal(TerminalSymbol::Id),
                        Symbol::Terminal(TerminalSymbol::Semi),
                    ],
                    vec![
                        Symbol::Terminal(TerminalSymbol::Vtype),
                        Symbol::Nonterminal(NonterminalSymbol::Assign),
                        Symbol::Terminal(TerminalSymbol::Semi),
                    ],
                ],
            ),
            (
                NonterminalSymbol::Assign,
                vec![vec![
                    Symbol::Terminal(TerminalSymbol::Id),
                    Symbol::Terminal(TerminalSymbol::Assign),
                ]],
            ),
        ]),
    }
}
fn main() {
    let parser = slr::parser::LRTable::new(&get_test_rules());
}
